version: '3'

services:
  android:
    build:
      context: .
      dockerfile: .
    environment:
      - NODE_VERSION=16.9.1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: 'yarn android'
    volumes:
        - .:/srv/android:rw
    working_dir: /srv/android
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: .
    environment:
      - NODE_VERSION=16.9.1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: 'yarn start'
    ports:
      - '127.0.0.1:8081:8081'
    volumes:
        - .:/srv/app:rw
    working_dir: /srv/app